### ISSUE TITLE
Travis Build no. 9.1 failure 

### ISSUE THREAD

**Issue by hemanth22** [hemanth22/ansible-role-filewatcher#7]
Error code: 1 

 JOB URL : https://travis-ci.org/hemanth22/ansible-role-filewatcher/jobs/621951599

**Comment by hemanth22** [comment]
**Correct Behaviour :** 

```
---
# tasks file for filewatcher
- name: Filewatch job.
  wait_for:
    timeout: 10
    path: "{{ role_path }}/files/hemanth.dat"
    msg: Timeout
  retries: 10
  register: file_res
  changed_when: false
  until: file_res is success
```

**Travis requirement:**

```
---
- name: Filewatch job.
  wait_for:
    timeout: 10
    path: /home/travis/build/hemanth22/hemanth22.filewatcher/files/hemanth.dat
    msg: Timeout
  retries: 10
  register: file_res
  changed_when: false
  until: file_res is success
```
